// Catálogo de amenazas paranormales que pueden activarse para atacar aviones.
//
// Cada amenaza tiene:
//   - category: "ufo" | "paranormal" | "creature"
//   - lat / lon: epicentro en la Tierra
//   - radius_km: radio de efecto (aviones dentro entran en BAJO ATAQUE)
//   - icon: emoji
//   - color: CSS para markers y halo
//   - power: intensidad (1-5), afecta tiempo de rescate y atracción
//   - desc: descripción para el HUD

export const THREATS = {
  // ─── OVNIS / UFO ──────────────────────────────────────────────────────────
  AREA_51: {
    category: "ufo",
    name: "Area 51",
    region: "Groom Lake, Nevada",
    lat: 37.235,
    lon: -115.811,
    radius_km: 250,
    icon: "🛸",
    color: "#00ffff",
    power: 4,
    desc: "Encuentros tipo IV. Programas TR-3B operativos.",
  },
  URITORCO: {
    category: "ufo",
    name: "Cerro Uritorco",
    region: "Capilla del Monte, Argentina",
    lat: -30.8617,
    lon: -64.5400,
    radius_km: 120,
    icon: "🛸",
    color: "#00ffff",
    power: 3,
    desc: "Punto histórico de avistamientos en Sudamérica.",
  },
  STONEHENGE: {
    category: "ufo",
    name: "Stonehenge",
    region: "Wiltshire, UK",
    lat: 51.1789,
    lon: -1.8262,
    radius_km: 100,
    icon: "🛸",
    color: "#00ffff",
    power: 3,
    desc: "Energías prehistóricas y luces extrañas en el cielo.",
  },
  ROSWELL: {
    category: "ufo",
    name: "Roswell",
    region: "Nuevo México, USA",
    lat: 33.394,
    lon: -104.523,
    radius_km: 180,
    icon: "🛸",
    color: "#00ffff",
    power: 4,
    desc: "El crash de 1947. Tecnología recuperada.",
  },
  NAZCA: {
    category: "ufo",
    name: "Líneas de Nazca",
    region: "Pampa Colorada, Perú",
    lat: -14.7390,
    lon: -75.130,
    radius_km: 130,
    icon: "🛸",
    color: "#00ffff",
    power: 3,
    desc: "Geoglifos visibles solo desde el cielo.",
  },

  // ─── ANOMALÍAS / PARANORMAL ──────────────────────────────────────────────
  BERMUDA: {
    category: "paranormal",
    name: "Triángulo de las Bermudas",
    region: "Atlántico Norte",
    lat: 25.0,
    lon: -71.0,
    radius_km: 800,
    icon: "🌀",
    color: "#ff00aa",
    power: 5,
    desc: "Anomalías electromagnéticas. Vuelo 19 sigue desaparecido.",
  },
  MARIANA: {
    category: "paranormal",
    name: "Fosa de las Marianas",
    region: "Pacífico Oeste",
    lat: 11.350,
    lon: 142.200,
    radius_km: 500,
    icon: "🌊",
    color: "#0088ff",
    power: 4,
    desc: "Profundidad abismal. Criaturas no clasificadas.",
  },
  TASMAN: {
    category: "paranormal",
    name: "Mar de Tasmania",
    region: "Australia / NZ",
    lat: -42.0,
    lon: 159.0,
    radius_km: 600,
    icon: "🌀",
    color: "#ff00aa",
    power: 4,
    desc: "Tormentas anómalas y huecos magnéticos.",
  },
  BAIKAL: {
    category: "paranormal",
    name: "Lago Baikal",
    region: "Siberia, Rusia",
    lat: 53.5,
    lon: 108.0,
    radius_km: 350,
    icon: "🌊",
    color: "#0088ff",
    power: 3,
    desc: "El lago más profundo del mundo. USOs documentados.",
  },
  DEVILS_SEA: {
    category: "paranormal",
    name: "Mar del Diablo",
    region: "Japón / Pacífico",
    lat: 27.0,
    lon: 142.0,
    radius_km: 500,
    icon: "🌀",
    color: "#ff00aa",
    power: 4,
    desc: "El Bermuda Triangle del Pacífico. Barcos y aviones desaparecidos.",
  },
  SKINWALKER: {
    category: "paranormal",
    name: "Skinwalker Ranch",
    region: "Utah, USA",
    lat: 40.250,
    lon: -109.880,
    radius_km: 90,
    icon: "👁️",
    color: "#9400d3",
    power: 4,
    desc: "Anomalías inexplicables. Portal interdimensional.",
  },

  // ─── CRIATURAS / CRYPTIDS ────────────────────────────────────────────────
  GODZILLA: {
    category: "creature",
    name: "Godzilla",
    region: "Bahía de Tokyo, Japón",
    lat: 35.6762,
    lon: 139.6503,
    radius_km: 150,
    icon: "🦖",
    color: "#22ff22",
    power: 5,
    desc: "Kaiju despierta. Ataque atómico inminente.",
  },
  NESSIE: {
    category: "creature",
    name: "Nessie",
    region: "Lago Ness, Escocia",
    lat: 57.3229,
    lon: -4.4244,
    radius_km: 60,
    icon: "🐉",
    color: "#88ff00",
    power: 2,
    desc: "El monstruo del Loch Ness. Avistado desde 1933.",
  },
  KRAKEN: {
    category: "creature",
    name: "Kraken",
    region: "Mar del Norte",
    lat: 60.0,
    lon: 2.0,
    radius_km: 400,
    icon: "🐙",
    color: "#aa00ff",
    power: 4,
    desc: "Tentáculos colosales. Hunde aviones y barcos.",
  },
  YETI: {
    category: "creature",
    name: "Yeti",
    region: "Everest, Himalaya",
    lat: 27.9881,
    lon: 86.9250,
    radius_km: 200,
    icon: "❄️",
    color: "#e0e0ff",
    power: 3,
    desc: "El abominable hombre de las nieves. Tormenta perpetua.",
  },
  MOTHMAN: {
    category: "creature",
    name: "Mothman",
    region: "Point Pleasant, WV",
    lat: 38.85,
    lon: -82.13,
    radius_km: 150,
    icon: "🦋",
    color: "#cc0033",
    power: 3,
    desc: "Criatura alada. Presagio de catástrofes.",
  },
  CHUPACABRA: {
    category: "creature",
    name: "Chupacabra",
    region: "Puerto Rico / Caribe",
    lat: 18.2208,
    lon: -66.5901,
    radius_km: 250,
    icon: "🩸",
    color: "#cc0000",
    power: 3,
    desc: "Cazadora oculta. Drena la sangre de su presa.",
  },
  BIGFOOT: {
    category: "creature",
    name: "Bigfoot",
    region: "Pacific Northwest",
    lat: 47.3,
    lon: -122.5,
    radius_km: 280,
    icon: "🦍",
    color: "#8b4513",
    power: 2,
    desc: "Sasquatch. Habita los bosques antiguos.",
  },
  CTHULHU: {
    category: "creature",
    name: "Cthulhu",
    region: "R'lyeh, Pacífico Sur",
    lat: -47.15,
    lon: -126.71,
    radius_km: 1000,
    icon: "🐙",
    color: "#440088",
    power: 5,
    desc: "El gran ancestro despierta. Locura cósmica.",
  },
};

export const THREAT_CATEGORIES = {
  ufo: { label: "OVNIS", icon: "🛸", color: "#00ffff" },
  paranormal: { label: "PARANORMAL", icon: "🌀", color: "#ff00aa" },
  creature: { label: "CRIATURAS", icon: "🦖", color: "#88ff00" },
};
